version: '3'
services:
  app:
    image: node:lts
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - '~/.ssh:/home/node/.ssh:ro'
    networks:
      - chainsaw-project
    environment:
      - SHELL=/bin/bash # Set the SHELL environment variable
    command: sleep infinity
  postgres:
    image: 'postgres:latest'
    ports:
      - '${DB_PORT:-5432}:${DB_PORT:-5432}'
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - 'chainsaw-project-postgres:/var/lib/postgresql/data'
    networks:
      - chainsaw-project
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME}']
      retries: 3
      timeout: 5s
  s3-storage:
    image: localstack/localstack:0.12.5
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

    ports:
      - '4566:4566'
    volumes:
      - './s3-storage/.init:/docker-entrypoint-initaws.d'
      - './s3-storage/.localstack:/tmp/localstack'
    networks:
      chainsaw-project:
        aliases:
          - s3-storage
          - s3storage.s3-storage

networks:
  chainsaw-project:
    driver: bridge

volumes:
  chainsaw-project-mysql:
    driver: local
  chainsaw-project-postgres:
    driver: local
