services:
  app:
    image: node:20-bookworm-slim
    init: true
    user: node
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    networks:
      - chainsaw-project
    environment:
      SHELL: /bin/bash
      DB_PRISMA_URL: postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_DATABASE}?schema=public
      DB_URL_NON_POOLING: postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_DATABASE}?schema=public
    command: sleep infinity
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    ports:
      - 127.0.0.1:${DB_PORT:-5432}:5432
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - chainsaw-project-postgres:/var/lib/postgresql/data
    networks:
      - chainsaw-project
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}']
      interval: 5s
      retries: 5
      timeout: 5s

networks:
  chainsaw-project:
    driver: bridge

volumes:
  chainsaw-project-postgres:
    driver: local
