# https://github.com/kentcdodds/kentcdodds.com/blob/main/.github/workflows/deployment.yml
name: Code Check
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
  pull_request:
    types:
      - opened
      - ready_for_review
      - synchronize
concurrency:
  group: ${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    if: github.event.pull_request.draft == false
    name: ⬣ Code Quality
    runs-on: ubuntu-latest
    env:
      DB_PRISMA_URL: postgresql://app:ci-only@localhost:5432/special_chainsaw?schema=public
      DB_URL_NON_POOLING: postgresql://app:ci-only@localhost:5432/special_chainsaw?schema=public
      NEXTAUTH_URL: http://localhost:3000
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
      - name: ⎔ Setup pnpm
        uses: pnpm/action-setup@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: 📥 Download deps
        run: corepack pnpm install --frozen-lockfile

      - name: 🔬 Lint
        run: corepack pnpm lint:strict

      - name: 💅 Prettier check
        run: corepack pnpm format:check

      - name: 📝 Generate prisma
        run: corepack pnpm generate

      - name: 🔎 Type check
        run: corepack pnpm typecheck

      - name: 🃏 Run jest
        run: corepack pnpm test -- --runInBand

      - name: 🔧 Run Build
        run: NEXTAUTH_SECRET="$(openssl rand -base64 32)" corepack pnpm build
